// Generated by CoffeeScript 1.9.1
var LayerMultiTouchGestures, test;

LayerMultiTouchGestures = require("MultiTouchEvents").LayerMultiTouchGestures;

test = new Layer({
  width: Screen.width / 2,
  height: Screen.width / 2
});

test.center();

test.pinch.enabled = true;

test.on(Events.Pinch, function() {
  if (test.pinch.totalDistance > 100) {
    test.pinch.totalDistance = 100;
  }
  if (test.pinch.totalDistance < 0) {
    test.pinch.totalDistance = 0;
  }
  return test.scale = Utils.modulate(test.pinch.totalDistance, [0, 100], [1, 2], true);
});
